name: Build and pish, with Buildx

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.0' # optional
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ROBOT_NAME }}
          password: ${{ secrets.ROBOT_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY }}/eryks-test/hellojs-buildx:${{ github.sha }}
          provenance: false
      -  
        name: Docker Metadata
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ secrets.REGISTRY }}/eryks-test/hellojs-buildx:${{ github.sha }}
      - 
        name: Sign image with a key
        run: |
          cosign sign --no --key env://COSIGN_PRIVATE_KEY ${{ secrets.REGISTRY }}/eryks-test/hellojs-buildx:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - 
        name: Validate image 
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY ${{ secrets.REGISTRY }}/eryks-test/hellojs-buildx:${{ github.sha }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
