name: build-and-push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Harbor
        run: |
          docker login --username '${{ secrets.ROBOT_NAME }}' --password '${{ secrets.ROBOT_TOKEN }}' ${{ secrets.REGISTRY }}
      -
        name: Docker build and push
        run: |
          docker build . -t hellojs:${{ github.sha }}
          docker tag hellojs:${{ github.sha }} ${{ secrets.REGISTRY }}/library/hellojs:${{ github.sha }}
          docker push ${{ secrets.REGISTRY }}/library/hellojs:${{ github.sha }}
          docker inspect --format='{{index .RepoDigests 0}}' hellojs:${{ github.sha }} > $digest
          echo digest

      -
        name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Check cosign instal
        run: cosign version

      - name: Sign image 
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${{ secrets.REGISTRY }}/library/hellojs@$digest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Validate image 
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY "${{ secrets.REGISTRY }}/library/hellojs:${{ github.sha }}"
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
